[package]
name = "chaindexing-macros"
version = "0.1.0"
edition = "2021"
description = "Procedural macros for Chaindexing"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
sqlparser = { version = "0.41" }
